# Project: TOYTL - GVM

# Target
BIN      = bin/gamevm_x64_exe

# Compiler settings
CXXFLAGS = -Ofast -Wall -W -m32 -march=native -mfpmath=sse -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations 
-D_GVM_HOST_OS=_GVM_HOST_HAIKU_INTEL_64 -D_GVM_DEBUGGING_

# Makefile settings
ARCH     = x64_haiku
MEXT     = $(ARCH)

include interpreter.make

