# Project: ExVM Multiplatform

# Target
BIN      = bin/gvm_x86

# Compiler settings
CXXFLAGS = -O3 -Wall -W -m32 -march=native -mfpmath=sse -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -I./

# Makefile settings
ARCH     = x86_linux
MEXT     = $(ARCH)

include interpreter.make

